---
- name: restart nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart nginx-exporter
  systemd:
    name: nginx-exporter
    state: restarted
